# Generated by Django 4.0.2 on 2022-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
