# Generated by Django 4.0.2 on 2022-02-21 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0002_movie_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
