# Generated by Django 4.0.2 on 2022-02-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
