# Generated by Django 4.0.2 on 2022-02-22 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
